### ISSUE TITLE
Groupped start states not rendered correctly

### ISSUE THREAD

**Issue by leventelist** [LunicLynx/vscode-lex#3]
Issue Type: <b>Bug</b>

This one dones't colorized right. The first half is red the rest seems to be okay.

```
<VALUE>{
    ^[[:space:]] {
    printf("SWALOW '%s'\n", yytext);
    //yylval->name = strdup(yytext);
    //return(cmd_value);
    }

    .+ {
        yylval->name = strdup(yytext);
        return(cmd_value);
    }

}
```

Extension version: 0.1.0
VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:39:22.915Z)
OS version: Linux x64 5.10.0-14-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31245 @ 3.30GHz (8 x 2442)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|11.65GB (1.63GB free)|
|Process Argv|--unity-launch --crash-reporter-id eea8acf2-18c9-4039-9512-ac2f4676abc3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdc:30486549

```

</details>

**Comment by LunicLynx** [comment]
Closed in favor of #1
